// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentFromFileContent(arg1) {
  return window['go']['main']['App']['AddTorrentFromFileContent'](arg1);
}

export function AddTorrentFromString(arg1) {
  return window['go']['main']['App']['AddTorrentFromString'](arg1);
}

export function GetTorrentInfo(arg1) {
  return window['go']['main']['App']['GetTorrentInfo'](arg1);
}

export function StandardizeSubtitle(arg1, arg2, arg3) {
  return window['go']['main']['App']['StandardizeSubtitle'](arg1, arg2, arg3);
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}

export function StopDownload(arg1, arg2) {
  return window['go']['main']['App']['StopDownload'](arg1, arg2);
}
