// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentFromFileContent(arg1:Array<number>):Promise<string>;

export function AddTorrentFromString(arg1:string):Promise<string>;
