// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTorrentFromFileContent(arg1:Array<number>):Promise<string>;

export function AddTorrentFromString(arg1:string):Promise<string>;

export function GetTorrentInfo(arg1:string):Promise<main.TorrentInfo>;
