// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {torrent} from '../models';

export function AddTorrentFromFileContent(arg1:Array<number>):Promise<string>;

export function AddTorrentFromString(arg1:string):Promise<string>;

export function GetTorrentInfo(arg1:string):Promise<torrent.Info>;

export function StandardizeSubtitle(arg1:Array<number>,arg2:string,arg3:number):Promise<Array<number>>;

export function StartDownload(arg1:string,arg2:string):Promise<void>;

export function StopDownload(arg1:string,arg2:string):Promise<void>;
