name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'TorPlayer-linux-amd64'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'TorPlayer-windows-amd64'
            platform:  'windows/amd64'
            os: 'windows-latest'
          # because of https://github.com/wailsapp/wails/issues/2290
          - name: 'TorPlayer'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.21'
          node-version: '18.13'